### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by elazarcoh** [Shinsentoh/vscode-manage-extensions-workspace#9]
Hi, 
I have the same idea for an extension, and was happy to land here and see it already implemented.
For my idea, I intended to use VSCode built-in settings to manage the bundles, what do you think of that idea?
The idea is to add a user-level setting
```jsonc
 "extension.bundles": {
     "Python”: {
         "extensions": [
              // list of extensions....
            ],
           // maybe more configurations here, e.g. 'inherit bundles'
        }
"extension.globalBundle": ... // not sure if needed actually, maybe?
```
then, in the vscode workspace settings I would have:
```jsonc
"extension.profile": {
   "bundles": [...]
}
```

This way everything uses VSCode internal sync mechanism, and is git friendly.

Do you think this is something that you would want for your extension to have/use?
Maybe you have already considered it and decided to not use this design, I guess.

I haven't tried your extension just yet, but I'm definitely going to give it a try. This was something I was missing.

**Comment by Shinsentoh** [comment]
Hi,

I did used the settings at first but whenever you had bundles defined, there was a huge block of json used for my extension only that was 5-10 times bigger than the whole vscode settings without it.

It is possible but not really nice to edit (and even worse when trying to edit another application's settings around all that json block)

The last downside is when you try to remove my extension, you would have to remove those blocks manually form the vscode settings.

**Comment by elazarcoh** [comment]
That makes sense. Thanks for explaining.
